version: '3'
services:
  web:
    container_name: 'enhanced_weather_app-web'
    image: '${WEATHER_APP_WEB_IMAGE}'
    command: gunicorn --workers=2 --timeout=0  --threads=4 enhanced_weather_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/enhanced_weather_app/static/
      - media_volume:/enhanced_weather_app/media/
    expose:
      - 80
    # network_mode: "host"

  nginx:
      container_name: 'enhanced_weather_app-nginx'
      image: '${WEATHER_APP_NGINX_IMAGE}'
      ports:
        - 80:80
      volumes:
        - static_volume:/enhanced_weather_app/static
        - media_volume:/enhanced_weather_app/media
volumes:
  static_volume:
  media_volume: