version: '3.1'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn enhanced_weather_app.wsgi:application --bind 0.0.0.0:8000 --timeout 0
    volumes:
      - static_volume:/enhanced_weather_app/static/
      - media_volume:/enhanced_weather_app/media/
    expose:
      - 80

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/enhanced_weather_app/static
      - media_volume:/enhanced_weather_app/media

volumes:
  static_volume:
  media_volume: