version: '3.1'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn --workers=2 --timeout=0  --threads=4 enhanced_weather_app.wsgi:application --bind 0.0.0.0:8000 
    volumes:
      - static_volume:/enhanced_weather_app/static/
      - media_volume:/enhanced_weather_app/media/
    expose:
      - 80
    network_mode: "host"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/enhanced_weather_app/static
      - media_volume:/enhanced_weather_app/media

volumes:
  static_volume:
  media_volume: